name: 'hyyy-toc-action'
description: '生成目录的md文件'
inputs:
  ignore:
    required: false
  owner:
    required: true
    description: '实际的仓库所有者'
  repo:
    required: true
    description: '仓库名'
  directory:
    required: false
    description: '要搜索的目录'
  token:
    required: true
    description: 'GITHUB_TOKEN'
runs:
  using: 'node20'
  main: 'index.js'
